[proxy-provider.attrs]
blocked_tries = 8
save_interval = 500  # updates
fetch_interval = 10_000  # s
shard_interval = 200  # updates
shard_threshold = 0.10
shard_length = 50
scoring_min_tries = 5
scoring_untested_score = 1
score_random_choice_exponent = 10
rejudge_interval = 2_160 # 6 hours

[proxy-provider]
cache_file = "proxies9.json"
fetcher_sites_json = "sites.json"
judges_json = "judges.json"
ip_resolvers_json = "ip_resolvers.json"

#[proxied-session]
#internet_access_test_url = "http://www.gstatic.com/generate_204"